#!/bin/bash
# GENERADO — NO EDITAR A MANO.
# Sale de data/sintaxis.json via tools/generar.sh
# Uso: source core/palabras.sh

PAED_condicionales=("SI" "FIN_SI" "SINO" "CONTRARIO" "ENTONCES")
PAED_bucles=("MIENTRAS" "FIN_MIENTRAS" "PARA" "FIN_PARA" "REPETIR" "HASTA" "HACER")
PAED_estructura=("ACCION" "ES" "FIN_ACCION" "FINACCION" "PROCESO" "AMBIENTE" "FUNCION" "FIN_FUNCION" "PROCEDIMIENTO" "FIN_PROCEDIMIENTO" "RETORNAR" "SEGUN" "FIN_SEGUN" "ABRIR" "CERRAR" "ARCHIVO" "REGISTRO" "FIN_REGISTRO")
PAED_salida=("ESCRIBIR")
PAED_entrada=("LEER")
PAED_tipos=("ENTEROS" "ENTERO" "REAL" "CARACTER" "CARACTERES" "BOOLEANO" "SECUENCIA" "VENTANA" "SALIDA" "ARREGLO" "CONSTANTE" "VAR" "DE" "AN" "N")
PAED_operadores=("Y" "O" "NO" "AND" "OR" "MOD" "DIV")
PAED_funciones_builtin=("TRUNC" "ABSO" "REDOND")
PAED_secuencias=("ARR" "AVZ" "CREAR" "VENTANA" "NFDS" "FDS")
PAED_booleanos=("V" "F")

PAED_procedimientos=("ESCRIBIR" "LEER" "ARR" "AVZ" "CREAR" "ABRIR" "CERRAR")
